name       : python-fasteners
version    : 0.16.3
release    : 8
source     :
    - https://pypi.io/packages/source/f/fasteners/fasteners-0.16.3.tar.gz : b1ab4e5adfbc28681ce44b3024421c4f567e705cc3963c732bf1cba3348307de
license    : Apache-2.0
component  : programming.python
summary    : A python package that provides useful locks
description: |
    A python package that provides useful locks.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-monotonic
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
    # no thanks
    rm -r $installdir/usr/lib/python%python3_version%/site-packages/fasteners/pywin32/
