name       : python-fasteners
version    : 0.17.3
release    : 9
source     :
    - https://pypi.io/packages/source/f/fasteners/fasteners-0.17.3.tar.gz : a9a42a208573d4074c77d041447336cf4e3c1389a256fd3e113ef59cf29b7980
homepage   : https://github.com/harlowja/fasteners
license    : Apache-2.0
component  : programming.python
summary    : A python package that provides useful locks
description: |
    A python package that provides useful locks.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-monotonic
    - python-six
build      : |
    python3 -m build --wheel --no-isolation
install    : |
    python3 -m installer --destdir=%installroot% dist/*.whl
