name       : python-fasteners
version    : '0.18'
release    : 14
source     :
    - https://pypi.io/packages/source/f/fasteners/fasteners-0.18.tar.gz : cb7c13ef91e0c7e4fe4af38ecaf6b904ec3f5ce0dda06d34924b6b74b869d953
homepage   : https://github.com/harlowja/fasteners
license    : Apache-2.0
component  : programming.python
summary    : A python package that provides useful locks
description: |
    A python package that provides useful locks.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-monotonic
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install

    # remove win32 files
    rm -rf $installdir/usr/lib/python%python3_version%/site-packages/fasteners/pywin32
