name       : python-fasteners
version    : '0.15'
release    : 5
source     :
    - https://files.pythonhosted.org/packages/15/d7/1e8b3270f21dffcaaf5a2889675e8b2fa35f8a43a5817a31d3820e8e9495/fasteners-0.15.tar.gz : 3a176da6b70df9bb88498e1a18a9e4a8579ed5b9141207762368a1017bf8f5ef
license    : Apache-2.0
component  : programming.python
summary    : A python package that provides useful locks
description: |
    A python package that provides useful locks.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-monotonic
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
