name       : python-fasteners
version    : 0.14.1
release    : 2
source     :
    - https://github.com/harlowja/fasteners/archive/0.14.1.tar.gz : 7ce40f6ed399ca533696b8a7ca02bf4497a98d81402304611f56b30d29208874
license    : Apache-2.0
component  : programming.python
summary    : A python package that provides useful locks
description: |
    A python package that provides useful locks.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-monotonic
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
