name       : python-fasteners
version    : '0.16'
release    : 7
source     :
    - https://pypi.io/packages/source/f/fasteners/fasteners-0.16.tar.gz : c995d8c26b017c5d6a6de9ad29a0f9cdd57de61ae1113d28fac26622b06a0933
license    : Apache-2.0
component  : programming.python
summary    : A python package that provides useful locks
description: |
    A python package that provides useful locks.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-monotonic
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
    # no thanks
    rm -r $installdir/usr/lib/python%python3_version%/site-packages/fasteners/pywin32/
